# permissions for end users to view crds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: crd-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-crd
    app.kubernetes.io/part-of: kubebuilder-crd
    app.kubernetes.io/managed-by: kustomize
  name: crd-viewer-role
rules:
- apiGroups:
  - makecrd.com.makecrd.com
  resources:
  - crds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - makecrd.com.makecrd.com
  resources:
  - crds/status
  verbs:
  - get
